spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            client-secret: "xxxxxxxxxxxxxxxxxxxxxx"
            scope:
              - email
              - profile

server:
  port: 8080 