spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 933135663345-he98t5h2phjirlr2n6ps04e6v79lg253.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

server:
  port: 8080 